"project_id" : "CROWDIN_PROJECT_ID"
"api_token" : "CROWDIN_PERSONAL_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"


"preserve_hierarchy": true

#
# Files configuration
#
files: [
 {
  "source" : "/app/src/main/res/values/strings.xml",
  "dest": "/mobile/android/strings.xml",
  "translation" : "/app/src/main/res/values-%locale%/strings.xml",
 }
]