name: Android Build

on:
  pull_request:
    branches: [ develop, acceptance ]
jobs:
  build:
    name: Build eXo Android Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 11  
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Setup Android SDK
        uses:
          android-actions/setup-android@v3
      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 6.1.1
          arguments: clean assembleDebug
