name: Android Autoupdate gems

on:
  schedule:
    - cron:  '0 0 * * 4' # Thu at 0 AM UTC
  workflow_dispatch:
jobs:
  build:
    name: Build eXo Android Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: acceptance
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      # Setup Ruby 3.0
      - name: Setup ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      # Install Bundler and dependencies gems
      - name: Install bundler and Up date dependencies
        run: gem install bundler && bundle update
      - name: Setup Android SDK
        uses:
          android-actions/setup-android@v3
      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: clean assembleDebug
      - name: Commiting new Gemfile
        run: |
          git add Gemfile Gemfile.lock
          git -c user.name='eXo Software Factory' -c user.email='exo-swf@exoplatform.com' commit -m "Update Gems $(date +%d-%m-%Y)" || true
      - name: Push changes to base branch
        run: git push origin acceptance:acceptance